spring:
  application:
    name: DiseaseForecasterPro
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1111
    url: jdbc:mysql://localhost:3306/forecasterpro?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&useSSL=false
  session:
    redis:
      repository-type: default
    timeout: 86400
  data:
    redis:
      port: 6379
      host: localhost
      database: 0


server:
  servlet:
    session:
      cookie:
        name: SESSION
        max-age: 604800
        http-only: true
  address: 0.0.0.0





# MyBatis-Plus 配置
mybatis-plus:
  # MyBatis-Plus 配置项
  configuration:
    # 是否开启驼峰命名自动映射，即从经典数据库列名 A_COLUMN 映射到经典 Java 属性名 aColumn
    map-underscore-to-camel-case: false    # 不开启驼峰命名自动映射
  # Mapper XML 文件的位置
  mapper-locations: classpath*:mapper/*.xml
  # 实体类的包路径，用于指定实体类的别名
  type-aliases-package: com.cosmos.diseaseforecasterpro.pojo   # 实体类所在的包路径，指定后可以使用实体类名作为别名
  # 全局配置
  global-config:
    # 数据库配置
    db-config:
      # 逻辑删除字段名
      logic-delete-field: deleted # 逻辑删除字段名
      # 逻辑已删除值（默认值：1）
      logic-delete-value: 1 # 逻辑删除的值
      # 逻辑未删除值（默认值：0）
      logic-not-delete-value: 0 # 逻辑未删除的值



bd:
  config:
    ocr-app-id: 115931857
    ocr-api-key: BOO6FZfMEi99JHuODCoMRXqw
    ocr-secret-key: qn35fWbmx0gc9cG7qdXs6pnLKrdMfAZN

    enhance-app-id: 116094898
    enhance-api-key: 5g2YQVPEHTyrtHi54wzCWL5g
    enhance-secret-key: QjVqipr6OYnpI6AlwViAuiPFbWcXR1pP



#下面是讯飞大模型相关配置
xf:
  config:
    host-url-websocket: https://spark-api.xf-yun.com/v1.1/chat   #大模型的基准请求
    app-id: 6fb94523
    api-secret: NTg3NDgwMDk0NGMwZGZjNjY4ODk1MjA5
    api-key: 1347a1ab698c3cbc5e57ea93dc0d3f52
    #    app-id: b8781c23
    max-response-time: 30     #设置最长等待时间为30s
    host-url-ocr: http://api.xf-yun.com/v1/private/sf8e6aca1     #OCR请求接口
    host-url-image-u: https://spark-api.cn-huabei-1.xf-yun.com/v2.1/image
    host-url-image-g: https://spark-api.cn-huabei-1.xf-yun.com/v2.1/tti
    #    api-secret: ZTk4MjMzYjM0YmYxZGQxYmEyZTc1Nzcy
    #    api-key: 5a15fb5c654f9315a941e51b65ecefa6


